"use server";

/**
 * F1 venue-name-search — server action entry point.
 *
 * Pipeline (3-Tier, sequential):
 *   Tier 1  internal DB (Phase 2 — skipped in MVP; isPublic flag TODO)
 *   Tier 2  Google Places Autocomplete (silent skip if GOOGLE_PLACES_API_KEY
 *           missing or monthly cap reached)
 *   Tier 3  Claude fallback (only when Tier 2 returns 0 hits or is disabled)
 *
 * Auth: requireUser → requireProjectMembership. Rate-limited per-project
 * per-minute via the in-memory bucket in `quota.ts`.
 *
 * Intentionally NOT exporting the internal shape of the upstream calls —
 * the client only consumes `VenueSearchHit[]` + envelope flags.
 */

import { z } from "zod";
import { requireUser, requireProjectMembership } from "@/server/auth";
import {
  MAX_QUERY_LENGTH,
  MIN_QUERY_LENGTH,
  type VenueSearchHit,
  type VenueSearchResponse,
} from "@/lib/venue-search/types";
import { normalizeHits } from "@/lib/venue-search/normalize";
import {
  fetchPlacesAutocomplete,
  isPlacesConfigured,
} from "@/lib/venue-search/places";
import { fetchClaudeFallback } from "@/lib/venue-search/claude-fallback";
import {
  canCallPlaces,
  checkRateLimit,
  incrementPlacesCounter,
} from "@/lib/venue-search/quota";
import { captureError } from "@/lib/sentry";

// Validation: bound the query length to protect upstream cost.
// `sessionToken` is a uuid generated by the client — we only check it's
// a reasonably-shaped opaque string (not its semantic validity).
const inputSchema = z.object({
  query: z.string().max(MAX_QUERY_LENGTH),
  sessionToken: z.string().min(1).max(128),
});

/**
 * Search venues by name. Returns up to 8 suggestion hits.
 *
 * Short queries (`< MIN_QUERY_LENGTH`) return `{ hits: [] }` without
 * calling any upstream — saves both latency and quota.
 *
 * Pipeline is sequential by design (H2 fix):
 *   Tier 2 (Places) is awaited first; Tier 3 (Claude) is only called
 *   when Tier 2 returns no hits. "fallback only" semantics.
 */
export async function searchVenuesByName(
  rawQuery: string,
  sessionToken: string,
): Promise<VenueSearchResponse> {
  const parsed = inputSchema.safeParse({ query: rawQuery, sessionToken });
  if (!parsed.success) {
    return { hits: [], error: "入力が正しくありません" };
  }

  const query = parsed.data.query.trim();
  if (query.length < MIN_QUERY_LENGTH) return { hits: [] };

  // Auth first — the rate-limit bucket is keyed on projectId so we need
  // that before we touch any upstream. Both helpers redirect() on fail
  // (handled by the server-action boundary), so we don't wrap in try.
  const user = await requireUser();
  const { projectId } = await requireProjectMembership(user.id);

  // Rate limit BEFORE upstream. Throttled requests still return a well-
  // formed envelope — UI shows a soft hint but doesn't lock input.
  if (!checkRateLimit(projectId).ok) {
    return { hits: [], throttled: true };
  }

  // Tier 2 gate: API key present AND monthly cap not reached.
  let placesAllowed = false;
  if (isPlacesConfigured()) {
    try {
      const { allowed } = await canCallPlaces(projectId);
      placesAllowed = allowed;
    } catch (err) {
      // Quota lookup failure shouldn't block Tier 3. Log and move on.
      captureError(err, { scope: "venue-search:quota-check" });
      placesAllowed = false;
    }
  }

  // Sequential upstream: Tier 2 first, Tier 3 only when Tier 2 returns nothing.
  // (H2 fix: "Tier 3 = fallback only" — parallel was billing Claude on every
  // call even when Places already returned hits.)
  const placesHits: VenueSearchHit[] = placesAllowed
    ? await fetchPlacesAutocomplete(query, parsed.data.sessionToken).catch(() => [])
    : [];

  const claudeHits: VenueSearchHit[] =
    placesHits.length === 0
      ? await fetchClaudeFallback(query).catch(() => [])
      : [];

  // Bump quota for Places calls that actually returned data. Queries that
  // errored out don't increment (those are failed hits from our side).
  if (placesAllowed && placesHits.length > 0) {
    try {
      await incrementPlacesCounter(projectId, 1);
    } catch (err) {
      // Counter write failure is non-fatal — we'd rather miss one
      // billing line than block the UX.
      captureError(err, { scope: "venue-search:quota-inc" });
    }
  }

  // Phase 2: prepend internal-DB hits here once Venue.isPublic exists.
  // TODO(phase2): const internalHits = await fetchInternalHits(query);
  const internalHits: VenueSearchHit[] = [];

  const hits = normalizeHits([internalHits, placesHits, claudeHits]);
  return { hits };
}
